# Default models used if API fetch fails or as user preference
# Find model IDs at https://openrouter.ai/models
defaults:
  transcription_model: "openai/whisper-large-v3"
  correction_model: "openai/gpt-4.1-mini"
  summarization_model: "openai/gpt-4.1-mini"

# Settings for fetching models from OpenRouter API
api_fetch:
  enabled: true # Set to false to disable dynamic fetching entirely
  cache_file: ".openrouter_models_cache.json" # Cache file location (relative to project root)
  cache_duration_hours: 24 # How long to use cache before re-fetching (e.g., 24 hours)
